name: CD Example

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Simular build
        run: echo "Construyendo proyecto..."

      - name: Simular deploy
        run: echo "Desplegando con henki :)"
